### ISSUE TITLE
Erweiterung um HmIP-BWTH

### ISSUE THREAD

**Issue by lahlor** [Nall-chan/HomematicEasyInstall#1]
Moin,

kannst du das ggf mal mit aufnehmen, da es dieses Gerät wohl noch nicht gibt.

> Gerät mit der Addresse XXXXXXXXXXXXXXXXXXXX hat keinen bekannten Kanaltyp (HEATING_CLIMATECONTROL_TRANSCEIVER).
>   Gerät mit Namen 'HmIP-BWTH XXXXXXXXXXXXXXXXXXXX' wird nicht erzeugt.
> --------------------------------------------------------------------
> Gerät mit der Addresse XXXXXXXXXXXXXXXXXXXX hat keinen bekannten Kanaltyp (CLIMATECONTROL_FLOOR_DIRECT_TRANSMITTER).
>   Gerät mit Namen 'HmIP-BWTH XXXXXXXXXXXXXXXXXXXX' wird nicht erzeugt.
> --------------------------------------------------------------------

das mit dem XXX war ich ;)

Gruß
Lars

**Comment by Nall-chan** [comment]
Ich benötige dann auch auch die Kanäle, und wenn möglich auch die Bedeutung der Datenpunkte bzw deren Profile.
Michael

Am 20. Februar 2018 22:20:03 MEZ schrieb lahlor <notifications@github.com>:
>Moin,
>
>kannst du das ggf mal mit aufnehmen, da es dieses Gerät wohl noch nicht
>gibt.
>
>> Gerät mit der Addresse XXXXXXXXXXXXXXXXXXXX hat keinen bekannten
>Kanaltyp (HEATING_CLIMATECONTROL_TRANSCEIVER).
>  Gerät mit Namen 'HmIP-BWTH XXXXXXXXXXXXXXXXXXXX' wird nicht erzeugt.
>--------------------------------------------------------------------
>Gerät mit der Addresse XXXXXXXXXXXXXXXXXXXX hat keinen bekannten
>Kanaltyp (CLIMATECONTROL_FLOOR_DIRECT_TRANSMITTER).
>  Gerät mit Namen 'HmIP-BWTH XXXXXXXXXXXXXXXXXXXX' wird nicht erzeugt.
>--------------------------------------------------------------------
>
>das mit dem XXX war ich ;)
>
>Gruß
>Lars
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Nall-chan/HomematicEasyInstall/issues/1

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by lahlor** [comment]
Gibt es dazu einen einfachen Weg dir die Daten herauszusuchen und zu übermitteln?

**Comment by Nall-chan** [comment]
Jein,
am besten die Kanäle per Hand in IPS anlegen z.B. über den Konfigurator.
Dann bei den Statusvariablen (die Namen entsprechen dem Datenpunkte) des neuen Gerätes die Profile kontrollieren bzw. anpassen.

Diese Auflistung alle Datenpunkte und Profile kann ich dann in das Modul einbauen.

Im Code sieht das nachher z.B. so aus:
  'CLIMATECONTROL_FLOOR_DIRECT_TRANSMITTER' => array(
        'SETPOINT' => array(
            'Name Raum' => 'Soll Temperatur',
            'Name Gewerk' => 'Soll Temperatur %2$s',
            'Profil' => '~Temperature.HM',
            'Action' => true
        )
    ),

Zusätzlich gibt es hier ein Auflistung von EQ3 über alle Kanäle und Datenpunkte.
http://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf
Teilweise macht es auch keinen Sinn Kanäle mit aufzunehmen, da sie keine (externe oder für IPS sinnvolle) Funktion bieten.

**Comment by Nall-chan** [comment]
CLIMATECONTROL_FLOOR_DIRECT_TRANSMITTER
CLIMATECONTROL_FLOOR_TRANSCEIVER
sind jetzt vorhanden.
